apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-watch-secrets
subjects:
- kind: ServiceAccount
  name: anya
  namespace: default
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: secrets-watcher
  apiGroup: rbac.authorization.k8s.io
