apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: resources-watcher
rules:
- apiGroups: [""]
  resources: ["pods", "services", "namespaces", "configmaps", "secrets", "events"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets", "statefulsets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch"]